version: 1.2.6

interface:
  endpointsMenu: true
  modelSelect: true
  parameters: false
  sidePanel: true
  presets: true
  prompts: true
  bookmarks: true
  multiConvo: true
  agents: true

fileConfig:
  endpoints:
    all:
      fileLimit: 500
      fileSizeLimit: 100
      rateLimitCount: 10000
      rateLimitDuration: 60
    openAI:
      fileLimit: 500
      fileSizeLimit: 100
      rateLimitCount: 10000
      rateLimitDuration: 60
    google:
      fileLimit: 500
      fileSizeLimit: 100
      rateLimitCount: 10000
      rateLimitDuration: 60
    anthropic:
      fileLimit: 500
      fileSizeLimit: 100
      rateLimitCount: 10000
      rateLimitDuration: 60
    Mistral:
      fileLimit: 500
      fileSizeLimit: 100
      rateLimitCount: 10000
      rateLimitDuration: 60
    assistants:
      fileLimit: 500
      fileSizeLimit: 100
      rateLimitCount: 10000
      rateLimitDuration: 60
    custom:
      fileLimit: 500
      fileSizeLimit: 100
      rateLimitCount: 10000
      rateLimitDuration: 60
  fileLimit: 5000
  fileSizeLimit: 100
  rateLimitCount: 10000
  rateLimitDuration: 600
  supportedMimeTypes:
    - "image/jpeg"
    - "image/png"
    - "image/gif"
    - "image/webp"
    - "image/svg+xml"
    - "text/plain"
    - "text/css"
    - "text/javascript"
    - "text/html"
    - "application/json"
    - "application/pdf"
    - "application/msword"
    - "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    - "application/vnd.ms-excel"
    - "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    - "video/mp4"
    - "video/quicktime"
    - "video/webm"

cache: true

ocr:
  enabled: true
  strategy: "mistral_ocr"
  mistralModel: "mistral-ocr-2503-xwgge"
  apiKey: "${AZURE_MISTRAL_OCR_API_KEY}"
  baseURL: "https://mistral-ocr-2503-xwgge.swedencentral.models.ai.azure.com/v1"  
  usingAzEndpoint: true


endpoints:
  
  agents:
    recursionLimit: 100
    maxIterations: 100
    langgraph:
      options:
        recursionLimit: 1000
        maxIterations: 1000
    timeout: 60000

  
  custom:
    - name: 'Mistral'
      apiKey: '${MISTRAL_API_KEY}'
      baseURL: 'https://api.mistral.ai/v1'
      models:
        default: 
          [
            'mistral-small-latest',
            'mistral-large-latest',
            'pixtral-large-latest'
          ]
        fetch: false
      titleConvo: true
      titleModel: 'mistral-small-latest'
      modelDisplayLabel: 'Mistral'
      dropParams: ['stop', 'user', 'frequency_penalty', 'presence_penalty']
      
    - name: "DALL-E"
      apiKey: "${OPENAI_API_KEY}"
      baseURL: "https://api.openai.com/v1"
      models:
        default:
          - dall-e-3
          - gpt-image-1
      fetch: false
      titleConvo: false
      modelDisplayLabel: "DALL-E"

balance:
  enabled: false
  threshold: 100

mcpServers:
  azure_doc_intel:
    type: "streamable-http"
    url: "https://librechat-ocr-function-production.up.railway.app/mcp"
    timeout: 120000
    initTimeout: 30000
    serverInstructions: "Use this tool to analyze documents from URLs and extract text, tables, and key-value pairs using Azure Document Intelligence."

  

  
